### ISSUE TITLE
Parse Error  on line 103 while plug-in activation in CTMP_Cookie_Consent.class.php

### ISSUE THREAD

**Issue by cfkone** [chrimm/ctmp-cookieconsent#1] opened 2016-02-13 07:40 UTC
There's an error while activating the plugin
Parse error: syntax error, unexpected '[' in /homepages/31/d93827400/htdocs/festeam.de/wp-content/plugins/ctmp-cookieconsent-master/CTMP_Cookie_Consent.class.php on line 103

Tested on Wordpress 4.4.2

**Comment by chrimm** [comment] 2016-02-13 16:50
This seems to be caused by an incompatibility with PHP prior to version 5.5.
It will be fixed in version 0.9.5 of the plugin.

Thank you for pointing me to this!

--Chris

**Closed as completed** 2016-02-13 16:58 UTC
